import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import zlib from "zlib";
import { builtinModules } from "node:module";

/**
 * Recursively list all files under `dir`, returning POSIX-style paths
 * relative to `dir` (no leading separator, forward slashes).
 * Replacement for the `glob` npm package using Node's built-in fs.
 */
async function listFilesRecursive(dir) {
    const entries = await fs.promises.readdir(dir, {
        recursive: true,
        withFileTypes: true,
    });
    const results = [];
    for (const entry of entries) {
        if (!entry.isFile()) continue;
        const parentDir = entry.parentPath ?? entry.path;
        const abs = path.join(parentDir, entry.name);
        const rel = path.relative(dir, abs).split(path.sep).join("/");
        results.push(rel);
    }
    return results;
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";
const compatibilityLock = JSON.parse(
    fs.readFileSync("document-worker.lock.json", "utf8"),
);
const readerSdtVersion = fs.readFileSync(
    "reader/reader/structured-document-text/src/version.js",
    "utf8",
);
if (
    Number(/SDT_PACK_VERSION\s*=\s*(\d+)/.exec(readerSdtVersion)?.[1]) !==
        compatibilityLock.enhancementPack.sdt.packVersion ||
    Number(
        /SDT_SCHEMA_VERSION\s*=\s*['"](\d+)\./.exec(readerSdtVersion)?.[1],
    ) !== compatibilityLock.enhancementPack.sdt.schemaMajorVersion
) {
    throw new Error(
        "Reader SDT versions do not match the Enhancement Pack contract",
    );
}

/**
 * Custom plugin: Inline worker code
 * Compiles the worker to a string and exports it
 */
const inlineWorkerPlugin = {
    name: "inline-worker-plugin",
    setup(build) {
        build.onResolve({ filter: /^virtual:worker$/ }, (args) => {
            return { path: args.path, namespace: "worker-code" };
        });

        build.onLoad({ filter: /.*/, namespace: "worker-code" }, async () => {
            const workerEntry = path.resolve("src/worker/worker.ts");
            const files = [...(await listFilesRecursive("src/worker"))];
            const absoluteWatchFiles = files.map((file) =>
                path.join("src/worker", file),
            );
            absoluteWatchFiles.push(
                ...(await listFilesRecursive("src/enhancement-pack")).map(
                    (file) => path.join("src/enhancement-pack", file),
                ),
                "document-worker.lock.json",
            );
            // Build the worker specifically
            const result = await esbuild.build({
                entryPoints: [workerEntry],
                bundle: true,
                write: false,
                format: "iife",
                target: "es2018",
                minify: prod,
                conditions: ["worker"],
                plugins: [], // No plugins for the worker itself to avoid recursion if not needed
                external: ["obsidian"],
            });

            const workerCode = result.outputFiles[0].text;
            // Escape backticks and other special chars if necessary, but JSON.stringify is safest for a string literal

            return {
                contents: `export default ${JSON.stringify(workerCode)};`,
                loader: "js",
                watchFiles: absoluteWatchFiles,
            };
        });
    },
};

/**
 * Custom plugin: Inline resources
 * When import "virtual:reader-resources", it will return a function that can be used to load resources.
 */
const inlineResourcePlugin = {
    name: "inline-resource-plugin",
    setup(build) {
        build.onResolve({ filter: /^virtual:reader-resources$/ }, (args) => {
            return { path: args.path, namespace: "reader-resources" };
        });

        build.onLoad(
            { filter: /.*/, namespace: "reader-resources" },
            async () => {
                const resourceDir = path.resolve(
                    "reader/reader/build/obsidian",
                );
                const packLock = JSON.parse(
                    fs.readFileSync("document-worker.lock.json", "utf8"),
                );
                const excluded = new Set(
                    packLock.enhancementPack.resources.map(
                        (r) => `document-worker/${r.path}`,
                    ),
                );
                const files = (await listFilesRecursive(resourceDir)).filter(
                    (file) => !excluded.has(file),
                );
                const absoluteWatchFiles = files.map((file) =>
                    path.join(resourceDir, file),
                );
                // Generate keys array
                const keys = files.map((f) => "./" + f.replace(/\\/g, "/"));

                // Generate Switch Case code block (Lazy Load)
                let switchCases = "";

                files.forEach((file) => {
                    const filePath = path.join(resourceDir, file);
                    const content = fs.readFileSync(filePath);

                    // Compress & Base64
                    const gzipped = zlib.gzipSync(content);
                    const base64 = gzipped.toString("base64");

                    const key = "./" + file.replace(/\\/g, "/");

                    switchCases += `    case "${key}": return "${base64}";\n`;
                });

                const contents = `
        export function resourceKeys() {
          return ${JSON.stringify(keys)};
        }
        
        export default function(key) {
          switch(key) {
${switchCases}
            default: return undefined;
          }
        }
      `;

                return {
                    contents,
                    loader: "js",
                    resolveDir: resourceDir,
                    watchFiles: absoluteWatchFiles,
                    watchDirs: [resourceDir],
                };
            },
        );
    },
};

/**
 * Custom plugin: Copy the reader/reader/build/obsidian/reader.js.LICENSE.txt to the output directory.
 */
const copyLicensePlugin = {
    name: "copy-license-plugin",
    setup(build) {
        build.onEnd(() => {
            try {
                const licenseFile = path.resolve(
                    "reader/reader/build/obsidian/reader.js.LICENSE.txt",
                );
                const licenseContent = fs.readFileSync(licenseFile, "utf-8");
                fs.writeFileSync("reader.js.LICENSE.txt", licenseContent);
            } catch {
                // The reader license is absent until the reader has been built.
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    platform: "browser",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    plugins: [inlineResourcePlugin, copyLicensePlugin, inlineWorkerPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
