/**
 * AUTO-GENERATED by scripts/generate-zotero-item-schema.js — do not edit.
 * Source: Zotero schema v42 (locales.en-US.itemTypes)
 *
 * Zotero's display name of each item type (e.g. conferencePaper →
 * "Conference Paper"). Read through `itemTypeLabel()`.
 */
export const ITEM_TYPE_LABELS: Readonly<Record<string, string>> = {
    annotation: "Annotation",
    artwork: "Artwork",
    attachment: "Attachment",
    audioRecording: "Audio Recording",
    bill: "Bill",
    blogPost: "Blog Post",
    book: "Book",
    bookSection: "Book Section",
    case: "Case",
    computerProgram: "Software",
    conferencePaper: "Conference Paper",
    dataset: "Dataset",
    dictionaryEntry: "Dictionary Entry",
    document: "Document",
    email: "E-mail",
    encyclopediaArticle: "Encyclopedia Article",
    film: "Film",
    forumPost: "Forum Post",
    hearing: "Hearing",
    instantMessage: "Instant Message",
    interview: "Interview",
    journalArticle: "Journal Article",
    letter: "Letter",
    magazineArticle: "Magazine Article",
    manuscript: "Manuscript",
    map: "Map",
    newspaperArticle: "Newspaper Article",
    note: "Note",
    patent: "Patent",
    podcast: "Podcast",
    preprint: "Preprint",
    presentation: "Presentation",
    radioBroadcast: "Radio Broadcast",
    report: "Report",
    standard: "Standard",
    statute: "Statute",
    thesis: "Thesis",
    tvBroadcast: "TV Broadcast",
    videoRecording: "Video Recording",
    webpage: "Web Page",
};

/** Zotero's display name of an item type; the type itself when it has none. */
export function itemTypeLabel(itemType: string): string {
    return ITEM_TYPE_LABELS[itemType] ?? itemType;
}
